spring.application.name=aaa-simple-webapp

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:aaa_db}
spring.datasource.username=${DB_NAME:aaa_db}
spring.datasource.password=${DB_NAME:aaa_db}
spring.datasource.hikari.schema=public